### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by weifeng-sc** [hourenyu/Trajectory-optimization-based-on-Bezier-polynomial-motion-planning-#1]
该程序为 x86_64-pc-linux-gnu 编译
报告错误到 <bug-make@gnu.org>
CMakeFiles/Makefile2:613: recipe for target '--original--Trajectory-optimization-based-on-Bezier-polynomial-motion-planning--master/Btraj/CMakeFiles/astar.dir/all' failed
make[1]: *** [--original--Trajectory-optimization-based-on-Bezier-polynomial-motion-planning--master/Btraj/CMakeFiles/astar.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Cycle-chang** [comment]
同问题 不知该如何解决

**Comment by Cycle-chang** [comment]
按路径在Makefile2中删去可正确编译

**Comment by hourenyu** [comment]
已解决
